spring:
  cloud:
    stream:
      defaultBinder: rabbit1 #Nome do binder
      bindings:
        #Filas
        messaging-input:
         destination: tjf-messaging-input
         group: requests
        messaging-output:
          destination: tjf-messaging-input
        #Filas de Erro  
        tjf-messaging-error-input:
          destination: tjf-messaging-errors
          group: errors
        tjf-messaging-error-output:
          destination: tjf-messaging-errors
          group: errors
          producer:
            requiredGroups: errors
      #Binder de conexão      
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbit:
                host: localhost #host do rabbitMQ
    
#Habilitar o Endpoint HTTP do serviço de recuperação de mensagens da fila de erro
management:
  endpoints:
    web:
      exposure:
        include: info,health,messaging                
                
server:
  port: 8080