version: '3'

services:

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "processdb"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"

  process:
    image: docker.totvs.io/tjf/process-service-discriminator
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - ./definitions:/definitions
    environment:
      serviceDiscriminatorDomainExchange: "anakin-exchange"
      serviceDiscriminatorDBHost: "postgres/processdb"
      serviceDiscriminatorDBUser: "admin"
      serviceDiscriminatorDBPass: "admin"
      serviceDiscriminatorRabbitHost: "rabbitmq"
      serviceDiscriminatorRabbitUsername: "guest"
      serviceDiscriminatorRabbitPassword: "guest"
