tjf:
  api:
    filter:
      fields:
        enabled: true

spring:

  h2:
    console:
      enabled: true
      path: /h2
      
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:swdroid
    username: swdroid
    password:

  cloud:
    stream:
      defaultBinder: rabbit1
      
      bindings:
        starship-input:
          destination: starship-input
          group: requests
        starship-output:
          destination: starship-input
      
      binders:
        rabbit1:
          type: jms
          environment:
            spring:
              activemq:
                username: karaf
                password: karaf
  
  jmx:
    enabled: false
  
server:
  port: 8180        